### ISSUE TITLE
Quitar .spyproject del rep

### ISSUE THREAD

**Issue by dzjavier** [ValeBertuni/CarmeYVale#1]
Hola! git les está versionando la carpeta del proyecto, seguramente les está faltando el archivo .gitignore. No debería versionarse esta carpeta.

**Comment by CarmeDominguez** [comment]
hola profe, que seria versionarse? como lo arreglamos?

**Comment by dzjavier** [comment]
Versionar sería que por cada commit que hacen, git crea un punto de referencia que marca las diferencias en los archivos cambiados. De esa manera pueden, tener versiones distintas y podrían volver atrás si lo necesitan. La idea es que la carpeta .spyproject no ser versione, por lo tanto no tiene que estar en el repo. Deben agregar un archivo .gitignore. Si se les complica, lo vemos en la clase

**Comment by ValeBertuni** [comment]
Pero cuando creamos el repo, añadimos la opcion del .gitignore, nose porque nos sale el .spyproject. 
Ya subimos todas las actividades, si quiere mañana nos ayuda con lo del .gitignore, gracias.

**Comment by CarmeDominguez** [comment]
Creo ahi esta solucionado sino, lo vemos mañana. 
Por otro lado acabamos de completar el tp1. Saludos

**Comment by CarmeDominguez** [comment]
para revisar @dzjavier (visto en clase)
